# adapters/base.py
class DataFrameAdapter:
    def read(self, source): ...
    def select(self, df, columns): ...
    def groupby(self, df, cols): ...
    def join(self, df1, df2): ...
    def count(self, df): ...