[build-system]
requires = ["maturin>=1.4"]
build-backend = "maturin"

[project]
name = "datalyzer"
version = "0.1.0"
description = "Processamento massivo com núcleo em Rust"
requires-python = ">=3.8"
packages = [{include = "py_processor", from = "src"}]

[tool.maturin]
module-name = "rust_core"